# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(verbose_name='student date of birth'),
        ),
    ]
